/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenfinal;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Index extends javax.swing.JFrame {
public static ArrayList<S_Guatemala> guatemala=new ArrayList<S_Guatemala>();
public static ArrayList<S_Jalapa> jalapa=new ArrayList<S_Jalapa>();
public static ArrayList<S_ElProgreso> progreso=new ArrayList<S_ElProgreso>();
public static int cont,o=0;
public static DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        this.Admin.setVisible(false);
        this.Ordenes.setVisible(false);
        model.addColumn("No");
        model.addColumn("Nombre");
        model.addColumn("Descripcion");
        model.addColumn("Sucursal");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Admin = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        Lista_Sucursal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_Nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_Precio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txt_Descripcion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Ordenes = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prueba = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Des = new javax.swing.JTextArea();
        pre = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        MyTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        NOMP = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dormidos_Pizza");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 51)));
        Admin.setVisible(true);
        Admin.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Sucursal.png"))); // NOI18N
        Admin.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 70, 150, 30));

        Lista_Sucursal.setBackground(new java.awt.Color(102, 102, 102));
        Lista_Sucursal.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        Lista_Sucursal.setForeground(new java.awt.Color(255, 255, 255));
        Lista_Sucursal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guatemala", "Jalapa", "El Progreso " }));
        Admin.getContentPane().add(Lista_Sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/pizza1.png"))); // NOI18N
        Admin.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Nombre.png"))); // NOI18N
        Admin.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 110, 30));

        Txt_Nombre.setBackground(new java.awt.Color(102, 102, 102));
        Txt_Nombre.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        Txt_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Txt_Nombre.setOpaque(false);
        Txt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_NombreActionPerformed(evt);
            }
        });
        Admin.getContentPane().add(Txt_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 180, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Precio.png"))); // NOI18N
        Admin.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 110, 40));

        Txt_Precio.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        Txt_Precio.setForeground(new java.awt.Color(255, 255, 255));
        Txt_Precio.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        Txt_Precio.setOpaque(false);
        Admin.getContentPane().add(Txt_Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 162, 101, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Descripcion.png"))); // NOI18N
        Admin.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 20));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));

        Txt_Descripcion.setColumns(20);
        Txt_Descripcion.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        Txt_Descripcion.setRows(5);
        jScrollPane1.setViewportView(Txt_Descripcion);

        Admin.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 327, 62));

        jButton1.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/icons8_save_32px.png"))); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Admin.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Tabla.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        Tabla.setForeground(new java.awt.Color(0, 0, 0));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Precio"
            }
        ));
        Tabla.setRowHeight(30);
        jScrollPane2.setViewportView(Tabla);

        Admin.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 134));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Admin1.png"))); // NOI18N
        Admin.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 340, 230));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/fondoAdmin.png"))); // NOI18N
        Admin.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 510));

        getContentPane().add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 530));

        Ordenes.setVisible(true);
        Ordenes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Ordenes.png"))); // NOI18N
        Ordenes.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 290, 80));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Sucursal.png"))); // NOI18N
        Ordenes.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 80, 140, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/pizza1.png"))); // NOI18N
        Ordenes.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, 30));

        prueba.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        Ordenes.getContentPane().add(prueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 131, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Descripcion.png"))); // NOI18N
        Ordenes.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 110, 40));

        Des.setColumns(20);
        Des.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 18)); // NOI18N
        Des.setRows(5);
        jScrollPane3.setViewportView(Des);

        Ordenes.getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 270, 70));

        pre.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        pre.setForeground(new java.awt.Color(255, 255, 255));
        pre.setText("PRECIO");
        Ordenes.getContentPane().add(pre, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 179, -1));

        MyTable.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        MyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MyTable.setRowHeight(30);
        jScrollPane5.setViewportView(MyTable);

        Ordenes.getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 110));

        jButton3.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/icons8_google_maps_32px.png"))); // NOI18N
        jButton3.setText("Jalapa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Ordenes.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, 30));

        jButton4.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/icons8_google_maps_32px.png"))); // NOI18N
        jButton4.setText("Guatemala");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Ordenes.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, 30));

        jButton5.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/icons8_google_maps_32px.png"))); // NOI18N
        jButton5.setText("El Progreso");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Ordenes.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, 30));

        jButton6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton6.setText("Ordenar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Ordenes.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        NOMP.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        NOMP.setForeground(new java.awt.Color(255, 255, 255));
        NOMP.setText("PIZZA");
        Ordenes.getContentPane().add(NOMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 330, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/fondoAdmin.png"))); // NOI18N
        Ordenes.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 580, 490));

        getContentPane().add(Ordenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/Fondo.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 610));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 4));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/icons8_administrative_tools_50px_1.png"))); // NOI18N
        jMenu1.setText("ADMINISTRACION");
        jMenu1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/icons8_purchase_order_50px_1.png"))); // NOI18N
        jMenu2.setText("      ORDENES");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(51, 51, 51));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgenes/icons8_close_window_50px.png"))); // NOI18N
        jMenu3.setText("        SALIR");
        jMenu3.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jMenu3.setHideActionText(true);
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        Ordenes.dispose();
        this.Admin.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        Admin.dispose();
        this.Ordenes.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        S_Guatemala pizza = new S_Guatemala(Txt_Nombre.getText(), Txt_Precio.getText(), Txt_Descripcion.getText());
        S_Jalapa pizzaj = new S_Jalapa(Txt_Nombre.getText(), Txt_Precio.getText(), Txt_Descripcion.getText());
        S_ElProgreso pizzap = new S_ElProgreso(Txt_Nombre.getText(), Txt_Precio.getText(), Txt_Descripcion.getText());

        String a = Lista_Sucursal.getSelectedItem().toString();

        if (a.equals("Guatemala")) {

            guatemala.add(pizza);

            String matriz[][] = new String[guatemala.size()][3];

            for (int i = 0; i < guatemala.size(); i++) {
                matriz[i][0] = guatemala.get(i).getNombreG();
                matriz[i][1] = guatemala.get(i).getPrecioG();
                matriz[i][2] = guatemala.get(i).getDescripcionG();
            }
            Tabla.setModel(new javax.swing.table.DefaultTableModel(
                    matriz,
                    new String[]{
                        "Nombre", "Descripcion", "Precio"
                    }
            ));
            Txt_Nombre.setText("");
            Txt_Precio.setText("");
            Txt_Descripcion.setText("");
        } else {
            if (a.equals("Jalapa")) {
                jalapa.add(pizzaj);
                String matriz1[][] = new String[jalapa.size()][3];

                for (int i = 0; i < jalapa.size(); i++) {
                    matriz1[i][0] = jalapa.get(i).NombreJ;
                    matriz1[i][1] = jalapa.get(i).PrecioJ;
                    matriz1[i][2] = jalapa.get(i).DescripcionJ;
                }

                Tabla.setModel(new javax.swing.table.DefaultTableModel(
                        matriz1,
                        new String[]{
                            "Nombre", "Descripcion", "Precio"
                        }
                ));
                Txt_Nombre.setText("");
                Txt_Precio.setText("");
                Txt_Descripcion.setText("");
            } else {
                //dsds
                progreso.add(pizzap);
                String matriz2[][] = new String[progreso.size()][3];

                for (int i = 0; i < progreso.size(); i++) {
                    matriz2[i][0] = progreso.get(i).NombreP;
                    matriz2[i][1] = progreso.get(i).PrecioP;
                    matriz2[i][2] = progreso.get(i).DescripcionP;
                }

                Tabla.setModel(new javax.swing.table.DefaultTableModel(
                        matriz2,
                        new String[]{
                            "Nombre", "Descripcion", "Precio"
                        }
                ));
                Txt_Nombre.setText("");
                Txt_Precio.setText("");
                Txt_Descripcion.setText("");
            }
            
        }
        prueba.removeAllItems();;
        
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
            cont=0; 
            for (int i = 0; i < jalapa.size(); i++) {
                int z;
                z = jalapa.size() - 1;
                String g = jalapa.get(i).getNombreJ();
                prueba.addItem(g);
                
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cont =1;
        for (int i = 0; i < guatemala.size(); i++) {
                int z;
                z = guatemala.size() - 1;
                String g = guatemala.get(i).getNombreG();
                prueba.addItem(g);
                
            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        cont =2;
        for (int i = 0; i < progreso.size(); i++) {
                int z;
                z = progreso.size() - 1;
                String g = progreso.get(i).getNombreP();
                prueba.addItem(g);
                   
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        o++;
        int p=prueba.getSelectedIndex();
        String h=p+"";
        pre.setText(h);
        String categoria1 = (String) prueba.getSelectedItem();
        int num=0;
        
        if(cont==0){    
          
                for (int i = 0; i < 1; i++) {
                 
                    String g = jalapa.get(p).getDescripcionJ();
                    String prec = jalapa.get(p).getPrecioJ();
                    Des.setText(g);
                    NOMP.setText("PIZZA: "+categoria1.toUpperCase());
                    pre.setText("PRECIO: Q. "+prec);
                    model.addRow(new Object[]{o,categoria1,g,"Jalapa"});
                    prueba.removeAllItems();;
                    
                }
        }else{
            if(cont==1){
                for (int i = 0; i < 1; i++) {
               
                String g = guatemala.get(p).getDescripcionG();
                String prec = guatemala.get(p).getPrecioG();
                Des.setText(g);
                NOMP.setText("PIZZA: "+categoria1.toUpperCase());
                pre.setText("PRECIO: Q. "+prec);
                model.addRow(new Object[]{o,categoria1,g,"Guatemala"});
                prueba.removeAllItems();;
        }
            }else{
                for (int i = 0; i < 1; i++) {
               
                String g = progreso.get(p).getDescripcionP();
                String prec = progreso.get(p).getPrecioP();
                Des.setText(g);
                NOMP.setText("PIZZA: "+categoria1.toUpperCase());
                pre.setText("PRECIO: Q. "+prec);
                model.addRow(new Object[]{o,categoria1,g,"El Progreso"});
                prueba.removeAllItems();;
                }
            
            }
        }
        MyTable.setModel(model);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void Txt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_NombreActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        System.exit( 0 );
    }//GEN-LAST:event_jMenu3MouseClicked
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame Admin;
    private javax.swing.JTextArea Des;
    private javax.swing.JComboBox<String> Lista_Sucursal;
    private javax.swing.JTable MyTable;
    private javax.swing.JLabel NOMP;
    private javax.swing.JInternalFrame Ordenes;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextArea Txt_Descripcion;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JTextField Txt_Precio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel pre;
    private javax.swing.JComboBox<String> prueba;
    // End of variables declaration//GEN-END:variables
}
